package tocaiagent;

import tocaiagent.core.*;
import java.util.*;
import java.io.*; // Added for file writing
import java.awt.Desktop; // Added for opening the browser

public class DFAGeneratorSystem {
    public DeterministicValidator validator;
    public AnalystAgent analyst;
    public ArchitectAgent architect;
    public DFARepairEngine repairEngine;
    public int maxRetries = 4;
    public String modelName = "qwen2.5-coder:1.5b";

    public DFAGeneratorSystem() {
        this.validator = new DeterministicValidator();
        this.analyst = new AnalystAgent(modelName);
        this.architect = new ArchitectAgent(modelName);
        this.repairEngine = new DFARepairEngine();
        System.out.println("--- System Initialized: Modular Architecture (" + modelName + ") ---");
    }

    /**
     * NEW: Generates an HTML file with Mermaid.js logic and opens it automatically.
     */
    public void visualizerTool(DFA dfa) {
        try {
            System.out.println("[Visualizer] Generating Interactive Diagram...");
            
            // 1. Build Mermaid Syntax
            StringBuilder sb = new StringBuilder();
            sb.append("stateDiagram-v2\n");
            sb.append("    direction LR\n"); // Left-to-Right layout
            
            // Add Start State
            sb.append("    [*] --> ").append(dfa.startState).append("\n");

            // Add Transitions (Grouped by Destination to combine arrows like '0,1')
            for (String src : dfa.transitions.keySet()) {
                Map<String, String> outMap = dfa.transitions.get(src);
                Map<String, List<String>> grouped = new HashMap<>();
                
                // Group inputs that go to the same destination
                for (Map.Entry<String, String> entry : outMap.entrySet()) {
                    grouped.computeIfAbsent(entry.getValue(), k -> new ArrayList<>()).add(entry.getKey());
                }

                for (Map.Entry<String, List<String>> group : grouped.entrySet()) {
                    String dest = group.getKey();
                    String label = String.join(",", group.getValue());
                    sb.append("    ").append(src).append(" --> ").append(dest).append(" : ").append(label).append("\n");
                }
            }

            // Style Accept States (Green color)
            sb.append("    classDef accept fill:#82E0AA,stroke:#333,stroke-width:2px;\n");
            for (String acc : dfa.acceptStates) {
                sb.append("    class ").append(acc).append(" accept\n");
            }

            // 2. Wrap in HTML
            String htmlContent = "<!DOCTYPE html><html><head>"
                    + "<style>body{font-family:sans-serif; text-align:center;} .mermaid{margin: 20px auto;}</style>"
                    + "<script type='module'>\n"
                    + "import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';\n"
                    + "mermaid.initialize({ startOnLoad: true });\n"
                    + "</script></head><body>"
                    + "<h2>DFA Visualization</h2>"
                    + "<p>Generated by TOC AI Agent</p>"
                    + "<div class='mermaid'>\n" 
                    + sb.toString() 
                    + "\n</div></body></html>";

            // 3. Write to File
            File file = new File("dfa_output.html");
            try (FileWriter writer = new FileWriter(file)) {
                writer.write(htmlContent);
            }

            System.out.println("[Visualizer] Diagram saved to: " + file.getAbsolutePath());

            // 4. Auto-Open in Browser
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().browse(file.toURI());
                System.out.println("[Visualizer] Browser opened automatically.");
            } else {
                System.out.println("[Visualizer] Auto-open not supported. Please open 'dfa_output.html' manually.");
            }

        } catch (Exception e) {
            System.out.println("[Visualizer] Error generating diagram: " + e.getMessage());
            e.printStackTrace();
        }
    }

    public void run(String userQuery) {
        long start = System.currentTimeMillis();
        LogicSpec spec = analyst.analyze(userQuery);
        String feedback = "";
        for (int i=0;i<maxRetries;i++) {
            DFA dfa = null;
            try {
                dfa = architect.design(spec, feedback);
            } catch (Exception e) {
                System.out.println("Architect failed: " + e.getMessage());
                continue;
            }
            ValidationResult vr = validator.validate(dfa, spec);
            if (vr.isValid) {
                visualizerTool(dfa);
                System.out.println("--- SUCCESS in " + (System.currentTimeMillis()-start)/1000.0 + "s ---");
                return;
            }
            System.out.println("   [System] Validation Failed. Attempting Logic Inversion...");
            Optional<DFA> inverted = repairEngine.tryInversionFix(dfa, spec, validator);
            if (inverted.isPresent()) {
                System.out.println("\n   [Auto-Repair] INVERSION TRIGGERED!");
                visualizerTool(inverted.get());
                System.out.println("--- SUCCESS (Via Inversion) in " + (System.currentTimeMillis()-start)/1000.0 + "s ---");
                return;
            }
            feedback = vr.message;
            System.out.println(">>> Retry " + (i+1) + "/" + maxRetries + "...");
        }
        System.out.println("--- FAILED after " + (System.currentTimeMillis()-start)/1000.0 + "s ---");
    }

    public static void main(String[] args) {
        DFAGeneratorSystem sys = new DFAGeneratorSystem();
        // You can change the query here to test different DFAs
        sys.run("Design a DFA that accepts strings ending with 'a'");
    }
}